Package Tool Changes to support versioning changes. 1. Support CONFLICTS in debian packages 2. Associated Build Changes 3. Better cmd line option support in package_tool

diff --git a/packaging/debian/package_tool/package_tool b/packaging/debian/package_tool/package_tool
--- a/packaging/debian/package_tool/package_tool
+++ b/packaging/debian/package_tool/package_tool
@@ -16,22 +16,12 @@ SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
 ## Load Functions ##
 source $SCRIPT_DIR/scripts/debian_build_lib.sh
 
-INPUT_DIR="$1"
-OUTPUT_DIR="$2"
-INPUT_PACKAGE_VERSION="$3"
-
-# Special Input Directories + Paths
-ABSOLUTE_PLACEMENT_DIR="${INPUT_DIR}/\$"
-PACKAGE_ROOT_PLACEMENT_DIR="${INPUT_DIR}/package_root"
-
-# Inputs
-INPUT_SAMPLES_DIR="$INPUT_DIR/samples"
-INPUT_DOCS_DIR="$INPUT_DIR/docs"
-DOCS_JSON_PATH="$INPUT_DIR/docs.json"
-CONFIG="$INPUT_DIR/debian_config.json"
-
 ## Debian Package Creation Functions ##
 execute(){
+    if ! parse_args_and_set_env_vars $@; then
+        exit 1
+    fi
+
     # Exit if required validation fails
     if ! validate_inputs; then
         exit 1
@@ -47,6 +37,60 @@ execute(){
     (cd ${PACKAGE_SOURCE_DIR}; debuild -us -uc)
 
     copy_files_to_output
+}
+
+parse_args_and_set_env_vars(){
+    OPTIND=1 # Reset in case getopts has been used previously in the shell.
+
+    while getopts ":n:v:i:o:h" opt; do
+      case $opt in
+        n)
+          PACKAGE_NAME="$OPTARG"
+          ;;
+        v)
+          PACKAGE_VERSION="$OPTARG"
+          ;;
+        i)
+          INPUT_DIR="$OPTARG"
+          ;;
+        o)
+          OUTPUT_DIR="$OPTARG"
+          ;;
+        h)
+          print_help
+          return 1
+          ;;
+        \?)
+          echo "Invalid option: -$OPTARG" >&2
+          return 1
+          ;;
+        :)
+          echo "Option -$OPTARG requires an argument." >&2
+          return 1
+          ;;
+      esac
+    done
+
+    return 0
+}
+
+print_help(){
+    echo "Usage: package_tool [-i <INPUT_DIR>] [-o <OUTPUT_DIRECTORY>] 
+    [-n <PACKAGE_NAME>] [-v <PACKAGE_VERSION>] [-h]
+
+    REQUIRED:
+        -i <INPUT_DIR>: Input directory conforming to package_tool conventions and debian_config.json
+        -o <OUTPUT_DIR>: Output directory for debian package and other artifacts
+
+    OPTIONAL:
+        -n <PACKAGE_NAME>: name of created package, will override value in debian_config.json
+        -v <PACKAGE_VERSION>: version of created package, will override value in debian_config.json
+        -h: Show this message
+
+    NOTES:
+        See Readme for more information on package_tool conventions and debian_config.json format
+        https://github.com/dotnet/cli/tree/master/packaging/debian/package_tool
+    "
 }
 
 validate_inputs(){
@@ -69,20 +113,35 @@ validate_inputs(){
         ret=1
     fi
 
+    if [[ -z "$INPUT_DIR" ]];
+        echo "ERROR: -i <INPUT_DIRECTORY> Not Specified"
+        ret=1
+    fi
+
+    if [[ -z "$OUTPUT_DIR" ]];
+        echo "ERROR: -o <OUTPUT_DIRECTORY> Not Specified."
+        ret=1
+    fi
+
     return $ret
 }
 
 parse_config_and_set_env_vars(){
     extract_base_cmd="python $SCRIPT_DIR/scripts/extract_json_value.py"
-
-    PACKAGE_NAME=$($extract_base_cmd $CONFIG "package_name")
     
-    # Override JSON Defined Version w/ Cmd Line ARG
-    if [ -z $INPUT_PACKAGE_VERSION ]; then
-        PACKAGE_VERSION=$($extract_base_cmd $CONFIG "release.package_version")
-    else
-        PACKAGE_VERSION=$INPUT_PACKAGE_VERSION
-    fi
+    # Arguments Take Precedence over Config
+    [ -z "$PACKAGE_VERSION" ] && PACKAGE_VERSION="$($extract_base_cmd $CONFIG "release.package_version")"
+    [ -z "$PACKAGE_NAME" ] && PACKAGE_NAME="$($extract_base_cmd $CONFIG "package_name")"
+
+    # Special Input Directories + Paths
+    ABSOLUTE_PLACEMENT_DIR="${INPUT_DIR}/\$"
+    PACKAGE_ROOT_PLACEMENT_DIR="${INPUT_DIR}/package_root"
+
+    # Inputs
+    INPUT_SAMPLES_DIR="$INPUT_DIR/samples"
+    INPUT_DOCS_DIR="$INPUT_DIR/docs"
+    DOCS_JSON_PATH="$INPUT_DIR/docs.json"
+    CONFIG="$INPUT_DIR/debian_config.json"
 
     PACKAGE_SOURCE_DIR="${OUTPUT_DIR}/${PACKAGE_NAME}-${PACKAGE_VERSION}"
     INSTALL_ROOT="/usr/share/${PACKAGE_NAME}"
